# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  imageName: 'attngangpu:$(Build.BuildId)'
  # define dockerId 
  # define dockerPassword
  # define userId

steps:
- script: |
    cd eval
    docker build -f dockerfile.gpu -t $(dockerId).azurecr.io/$(imageName) .
    docker login $(dockerid).azurecr.io -u $(userId) -p $pswd
    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: $(dockerPassword)
  displayName: 'Build and push Docker image'